version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - db
    env_file: .env
  db:
    image: postgres:15.3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./startup.sh:/docker-entrypoint-initdb.d/startup.sh
    env_file: .env

volumes:
  postgres_data:
