project_name: slack-viewer
release:
  github:
    owner: iapolinario
    name: slack-viewer
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    goarm:
      - 6
    ldflags:
      - -s -w
    hooks:
      pre: go mod download
archives:
  - id: archive
    format: tar.gz
    files:
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
