apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: "slackviewer"
  iapolinario.com/owner: "devops"
  iapolinario.com/slack: "guild-slackviewer"
resources:
  - ../base
generatorOptions:
  disableNameSuffixHash: true
patches:
  - target:
      group: image.toolkit.fluxcd.io
      version: v1beta1
      kind: ImageUpdateAutomation
      name: slackviewer
    patch: |-
      - op: replace
        path: /spec/update/path
        value: ./deploy/development
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: slackviewer-ingress
    patch: |-
      - op: replace
        path: "/metadata/annotations/external-dns.alpha.kubernetes.io~1host"
        value: slackviewer.development.shiftdev.io
      - op: replace
        path: /spec/rules/0/host
        value: slackviewer.development.shiftdev.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: slackviewer.development.shiftdev.io
