apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slackviewer-secrets
  namespace: slackviewer
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: parameter-store
    kind: ClusterSecretStore
  target:
    name: slackviewer-secrets
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY
      remoteRef:
        key: /slackviewer/ACCESS_KEY
    - secretKey: SECRET_KEY
      remoteRef:
        key: /slackviewer/SECRET_KEY
    - secretKey: REACT_APP_OKTA_CLIENT_ID
      remoteRef:
        key: /slackviewer/REACT_APP_OKTA_CLIENT_ID
    - secretKey: REACT_APP_OKTA_ORG
      remoteRef:
        key: /slackviewer/REACT_APP_OKTA_ORG
    - secretKey: REACT_APP_OKTA_SCOPES
      remoteRef:
        key: /slackviewer/REACT_APP_OKTA_SCOPES
    - secretKey: REACT_APP_API_BASE_URL
      remoteRef:
        key: /slackviewer/REACT_APP_API_BASE_URL