apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: "slackviewer"
  iapolinario.com/owner: "devops"
  iapolinario.com/slack: "guild-slackviewer"

resources:
  - external-secrets.yaml
  - deployment-slackviewer-backend.yaml
  - deployment-slackviewer-frontend.yaml
  - ingress.yaml
  - notifications.yaml
