apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slackviewer-provider
  namespace: flux-system
spec:
  channel: slackviewer-alerts-staging
  secretRef:
    name: slack-url-kube-alerts
  type: slack
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: slackviewer-slack-alert
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      namespace: slackviewer
      name: "*"
    - kind: ImageUpdateAutomation
      name: "*"
      namespace: slackviewer
    - kind: Kustomization
      name: "*"
      namespace: slackviewer
  providerRef:
    name: slackviewer-provider